version: "3.7"         

services:        
  db:             
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: database
    environment:
      MSSQL_SA_PASSWORD: Un!q@to2023      
      ACCEPT_EULA: Y
    networks:
      - salihnet

  myapp:
    image: salihijk/quickdbtest
    container_name: myapp
    restart: always
    depends_on:
      - db
    ports:
      - "80:80"
    networks:
      - salihnet

networks:    
  salihnet:      
    driver: bridge