version: "3.7"         

services:        
  localhost:             
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: database
    environment:
      MSSQL_SA_PASSWORD: Un!q@to2023  
      MSSQL_DATABASE: db_vero_digital     
      MSSQL_USER: sa
    networks:
      - salihnet

  myapp:
    image: salihijk/QuickDbTest:latest
    container_name: myapp
    restart: always
    depends_on:
      - localhost
    ports:
      - "1443:1443"
    networks:
      - salihnet

networks:    
  salihnet:      
    driver: bridge